// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcSb6DpIgX41AdZsW2RJYjqwOb4Zd__MM',
    appId: '1:254772773044:web:1ec075c8375aa6a394d7e1',
    messagingSenderId: '254772773044',
    projectId: 'muuguzi-app',
    authDomain: 'muuguzi-app.firebaseapp.com',
    storageBucket: 'muuguzi-app.firebasestorage.app',
    measurementId: 'G-80NP6XQ23W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0m7xoyxow7qMl7dz2m6maFXTPKkkS4qA',
    appId: '1:254772773044:android:fbc2232af5759faa94d7e1',
    messagingSenderId: '254772773044',
    projectId: 'muuguzi-app',
    storageBucket: 'muuguzi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEygvrfaVs3sS_1rkD1zecOPPvlVMYlkU',
    appId: '1:254772773044:ios:982619e24519dc4c94d7e1',
    messagingSenderId: '254772773044',
    projectId: 'muuguzi-app',
    storageBucket: 'muuguzi-app.firebasestorage.app',
    iosBundleId: 'com.example.muuguzi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEygvrfaVs3sS_1rkD1zecOPPvlVMYlkU',
    appId: '1:254772773044:ios:982619e24519dc4c94d7e1',
    messagingSenderId: '254772773044',
    projectId: 'muuguzi-app',
    storageBucket: 'muuguzi-app.firebasestorage.app',
    iosBundleId: 'com.example.muuguzi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcSb6DpIgX41AdZsW2RJYjqwOb4Zd__MM',
    appId: '1:254772773044:web:3500b248a5ae5e5294d7e1',
    messagingSenderId: '254772773044',
    projectId: 'muuguzi-app',
    authDomain: 'muuguzi-app.firebaseapp.com',
    storageBucket: 'muuguzi-app.firebasestorage.app',
    measurementId: 'G-P21RSL0CB5',
  );
}
